spring:
  cache: 
    type: redis
  redis: 
    host: localhost
    port: 6379
    timeOfLife: 60000
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017

jwt:
  expiration: 1800000
  secret: springbootjwtcoderhouse
  
mail:
  host: smtp.gmail.com
  port: 587
  username: coderhousebackendjava@gmail.com
  password: sdjcouhhtdaifhke
  properties:
    mail:
      smtp:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls:
          enable: true

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi/index.html

server:
  port: 8080
